version: "3.7"
services:
  app:
    build:
      args:
        user: hanun
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: kuis2
    container_name: kuis2-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - kuis2

  db:
    image: mysql:8.0
    container_name: kuis2-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: kuis2
      MYSQL_ROOT_PASSWORD: hanun
      MYSQL_PASSWORD: hanun
      MYSQL_USER: hanun
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - kuis2

  nginx:
    image: nginx:alpine
    container_name: kuis2-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - kuis2

networks:
  kuis2:
    driver: bridge
